network:
  name: sample_network
  description: Demo two-section pipeline with optional control valve.
  direction: forward
  boundary_pressure: 8500000.0
  gas_flow_model: isothermal
  fluid:
    name: natural_gas
    phase: gas
    mass_flow_rate: 2.5
    volumetric_flow_rate: null
    temperature: 320
    pressure: 8500000.0
    density: 35.0
    molecular_weight: 18.0
    z_factor: 0.9
    specific_heat_ratio: 1.3
    viscosity: 1.1e-05
    standard_flow_rate: null
    vapor_pressure: 500000.0
    critical_pressure: 45000000.0
  sections:
  - id: inlet_to_valve
    schedule: '40'
    pipe_NPD: 6.0
    roughness: 4.6e-05
    length: 120.0
    elevation_change: 15.0
    erosional_constant: 100
    fitting_type: LR
    fittings:
    - type: elbow_90
      count: 2
    - type: tee_through
      count: 1
    pipe_diameter: 0.15408
    inlet_diameter: 0.15408
    outlet_diameter: 0.15408
    fitting_K: null
    pipe_length_K: null
    user_K: 2.0
    piping_and_fitting_safety_factor: 1.0
    total_K: null
    user_specified_fixed_loss: null
    control_valve:
      tag: CV-101
      pressure_drop: 7000.0
      cv: 1.954767997708578
    calculation_result:
      pressure_drop:
        pipe_and_fittings: 1753.1438064815206
        elevation_change: 0.0
        control_valve: 7000.0
        orifice: null
        user_fixed: null
        total: 8753.143806481521
        per_100m: 1460.9531720679338
      summary:
        inlet:
          pressure: 8500000.0
          temperature: 320
          density: 63.89468861762581
          mach_number: 0.008739006011696545
          velocity: 3.8308005702320447
          erosional_velocity: 15.261351841689013
          flow_momentum: 937.6566645564171
          remarks: OK
        outlet:
          pressure: 8491246.856193518
          temperature: 320
          density: 63.82889104139753
          mach_number: 0.008739006011696545
          velocity: 3.8308005702320447
          erosional_velocity: 15.26921584570983
          flow_momentum: 936.6910829533622
          remarks: OK
  - id: valve_to_export
    schedule: '80'
    pipe_NPD: 8.0
    roughness: 4.6e-05
    orifice:
      tag: FE-201
      d_over_D_ratio: 0.35
      pressure_drop: 16196.252695568866
    pipe_diameter: 0.1937
    inlet_diameter: 0.1937
    outlet_diameter: 0.1937
    calculation_result:
      pressure_drop:
        pipe_and_fittings: null
        elevation_change: 0.0
        control_valve: null
        orifice: 16196.252695568866
        user_fixed: null
        total: 16196.252695568866
        per_100m: null
      summary:
        inlet:
          pressure: 8491246.856193518
          temperature: 320
          density: 63.82889104139753
          mach_number: 0.005529620623495607
          velocity: 2.423945447491632
          erosional_velocity: 15.26921584570983
          flow_momentum: 375.0273854150177
          remarks: OK
        outlet:
          pressure: 8475050.603497948
          temperature: 320
          density: 63.70714345048508
          mach_number: 0.005529620623495607
          velocity: 2.423945447491632
          erosional_velocity: 15.283799005738041
          flow_momentum: 374.3120560405678
          remarks: OK
  summary:
    state:
      inlet:
        pressure: 8500000.0
        temperature: 320
        density: 63.89468861762581
        mach_number: 0.008739006011696545
        velocity: 3.8308005702320447
        erosional_velocity: 15.261351841689013
        flow_momentum: 937.6566645564171
        remarks: OK
      outlet:
        pressure: 8475050.603497948
        temperature: 320
        density: 63.70714345048508
        mach_number: 0.005529620623495607
        velocity: 2.423945447491632
        erosional_velocity: 15.283799005738041
        flow_momentum: 374.3120560405678
        remarks: OK
    pressure_drop:
      pipe_and_fittings: 1753.1438064815206
      elevation_change: 0.0
      control_valve: 7000.0
      orifice: 16196.252695568866
      user_fixed: null
      total: 24949.39650205039
      per_100m: 1460.9531720679338
