network:
  name: sample_network
  description: Phenol Test
  direction: forward
  boundary_pressure: 202333.0
  gas_flow_model: null
  fluid:
    name: liquid
    mass_flow_rate: 25.142666666666667
    volumetric_flow_rate: 0.03209428984767254
    phase: liquid
    temperature: 376.57
    pressure: 202333.0
    density: 783.4
    molecular_weight: 0.0
    z_factor: 1.0
    specific_heat_ratio: 1.0
    viscosity: 0.000247
    standard_flow_rate: null
    vapor_pressure: null
    critical_pressure: null
  sections:
  - id: '1'
    schedule: '40'
    roughness: 4.6e-05
    length: 37.599
    elevation_change: -23.59
    fitting_type: LR
    fittings:
    - type: elbow_90
      count: 9
    - type: tee_elbow
      count: 1
    - type: pipe_entrance_normal
      count: 1
    pipe_diameter: 0.20274
    inlet_diameter: 0.20274
    outlet_diameter: 0.20274
    fitting_K: 2.9883884897798954
    pipe_length_K: 2.8524678346209575
    user_K: null
    piping_and_fitting_safety_factor: null
    total_K: 5.840856324400853
    user_specified_fixed_loss: null
    pipe_NPD: 8.0
    erosional_constant: 100
    mach_number: null
    calculation_result:
      pressure_drop:
        fitting_K: 2.9883884897798954
        pipe_length_K: 2.8524678346209575
        user_K: null
        piping_and_fitting_safety_factor: null
        total_K: 5.840856324400853
        reynolds_number: 639271.0845244966
        flow_scheme: turbulent
        frictional_factor: 0.015380976323600443
        pipe_and_fittings: 2261.2475251217984
        elevation_change: -181230.8734999
        control_valve: null
        orifice: null
        user_fixed: null
        total: -178969.6259747782
        per_100m: 6014.116133731744
      summary:
        inlet:
          pressure: 202333.0
          temperature: 376.57
          density: 783.4
          mach_number: null
          velocity: 0.9941662252262125
          erosional_velocity: 4.358465376064942
          flow_momentum: 774.286303080312
          remarks: OK
        outlet:
          pressure: 381302.6259747782
          temperature: 376.57
          density: 783.4
          mach_number: null
          velocity: 0.9941662252262125
          erosional_velocity: 4.358465376064942
          flow_momentum: 774.286303080312
          remarks: OK
      flow:
        volumetric_actual: 0.03209428984767254
        volumetric_standard: null
  - id: '2'
    schedule: '40'
    roughness: 4.6e-05
    length: 8.639
    elevation_change: -3.208
    fitting_type: LR
    fittings:
    - type: elbow_90
      count: 3
    - type: tee_elbow
      count: 1
    - type: block_valve_full_line_size
      count: 1
    - type: outlet_swage
      count: 1
    pipe_diameter: 0.20274
    inlet_diameter: 0.20274
    outlet_diameter: 0.10226
    fitting_K: 6.490866116891514
    pipe_length_K: 0.6554022613178663
    user_K: null
    piping_and_fitting_safety_factor: null
    total_K: 7.14626837820938
    user_specified_fixed_loss: 5080.0
    pipe_NPD: 8.0
    erosional_constant: 100
    mach_number: null
    calculation_result:
      pressure_drop:
        fitting_K: 6.490866116891514
        pipe_length_K: 0.6554022613178663
        user_K: null
        piping_and_fitting_safety_factor: null
        total_K: 7.14626837820938
        reynolds_number: 639271.0845244966
        flow_scheme: turbulent
        frictional_factor: 0.015380976323600443
        pipe_and_fittings: 2766.628861691739
        elevation_change: -24645.55498888
        control_valve: null
        orifice: null
        user_fixed: 5080.0
        total: -16798.926127188264
        per_100m: 32024.87396332607
      summary:
        inlet:
          pressure: 381302.6259747782
          temperature: 376.57
          density: 783.4
          mach_number: null
          velocity: 0.9941662252262125
          erosional_velocity: 4.358465376064942
          flow_momentum: 774.286303080312
          remarks: OK
        outlet:
          pressure: 398101.55210196646
          temperature: 376.57
          density: 783.4
          mach_number: null
          velocity: 0.9941662252262125
          erosional_velocity: 4.358465376064942
          flow_momentum: 774.286303080312
          remarks: OK
      flow:
        volumetric_actual: 0.03209428984767254
        volumetric_standard: null
  summary:
    state:
      inlet:
        pressure: 202333.0
        temperature: 376.57
        density: 783.4
        mach_number: null
        velocity: 0.9941662252262125
        erosional_velocity: 4.358465376064942
        flow_momentum: 774.286303080312
        remarks: OK
      outlet:
        pressure: 398101.55210196646
        temperature: 376.57
        density: 783.4
        mach_number: null
        velocity: 0.9941662252262125
        erosional_velocity: 4.358465376064942
        flow_momentum: 774.286303080312
        remarks: OK
    pressure_drop:
      fitting_K: null
      pipe_length_K: null
      user_K: null
      piping_and_fitting_safety_factor: null
      total_K: null
      reynolds_number: null
      flow_scheme: null
      frictional_factor: null
      pipe_and_fittings: 5027.8763868135375
      elevation_change: -205876.42848878
      control_valve: 0.0
      orifice: 0.0
      user_fixed: 5080.0
      total: -195768.55210196646
      per_100m: 38038.99009705782
    flow:
      volumetric_actual: 0.03209428984767254
      volumetric_standard: null
